server:
  port: 9999

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword

logging:
  level:
    ROOT: INFO
    com:
      finxsoft: INFO
    io:
      r2dbc:
        h2:
          H2Connection: ERROR